title: Dara Issa
logo: images/profile.png
description: Portfolio
theme: jekyll-theme-minimal
link: https://public.tableau.com/app/profile/dara.issa/viz/EVDashboard_17057754401430/Dashboard1?publish=yes
